---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  # - - "@semantic-release/changelog"
  #   - changelogTitle: Changelog
  #     changelogFile: CHANGELOG.md
  # - - "@semantic-release/git"
  #   - assets: "CHANGELOG.md"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
      - "package.json"
      - "package-lock.json"
branches:
  - name: main
